[ 2024-02-26 14:11:21,427 ] 96 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.31.160:8080
[ 2024-02-26 14:11:21,428 ] 96 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2024-02-26 14:11:45,367 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:11:45] "GET / HTTP/1.1" 200 -
[ 2024-02-26 14:11:45,441 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:11:45] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2024-02-26 14:15:01,091 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:15:01] "[33mGET /predic HTTP/1.1[0m" 404 -
[ 2024-02-26 14:15:17,309 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:15:17] "[33mGET /predicdata HTTP/1.1[0m" 404 -
[ 2024-02-26 14:15:29,930 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:15:29] "GET /predictdata HTTP/1.1" 200 -
[ 2024-02-26 14:15:30,283 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:15:30] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2024-02-26 14:16:31,735 ] 828 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "d:\ML\github\ML-Example-docker-image\src\pipeline\predict_pipeline.py", line 18, in predict
    data_scaled=preprocessor.transform(features)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\_set_output.py", line 295, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1014, in transform
    Xs = self._call_func_on_transformers(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py", line 823, in _call_func_on_transformers
    return Parallel(n_jobs=self.n_jobs)(jobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\parallel.py", line 67, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\joblib\parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\joblib\parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\parallel.py", line 129, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\pipeline.py", line 1283, in _transform_one
    res = transformer.transform(X, **params.transform)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\pipeline.py", line 905, in transform
    Xt = transform.transform(Xt, **routed_params[name].transform)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\_set_output.py", line 295, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1032, in transform
    if self._drop_idx_after_grouping is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OneHotEncoder' object has no attribute '_drop_idx_after_grouping'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ML\github\ML-Example-docker-image\app.py", line 36, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ML\github\ML-Example-docker-image\src\pipeline\predict_pipeline.py", line 23, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [d:\ML\github\ML-Example-docker-image\src\pipeline\predict_pipeline.py] line number [18] error message['OneHotEncoder' object has no attribute '_drop_idx_after_grouping']
[ 2024-02-26 14:16:31,742 ] 828 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "d:\ML\github\ML-Example-docker-image\src\pipeline\predict_pipeline.py", line 18, in predict
    data_scaled=preprocessor.transform(features)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\_set_output.py", line 295, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1014, in transform
    Xs = self._call_func_on_transformers(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py", line 823, in _call_func_on_transformers
    return Parallel(n_jobs=self.n_jobs)(jobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\parallel.py", line 67, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\joblib\parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\joblib\parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\parallel.py", line 129, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\pipeline.py", line 1283, in _transform_one
    res = transformer.transform(X, **params.transform)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\pipeline.py", line 905, in transform
    Xt = transform.transform(Xt, **routed_params[name].transform)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\_set_output.py", line 295, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1032, in transform
    if self._drop_idx_after_grouping is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OneHotEncoder' object has no attribute '_drop_idx_after_grouping'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ML\github\ML-Example-docker-image\app.py", line 36, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ML\github\ML-Example-docker-image\src\pipeline\predict_pipeline.py", line 23, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [d:\ML\github\ML-Example-docker-image\src\pipeline\predict_pipeline.py] line number [18] error message['OneHotEncoder' object has no attribute '_drop_idx_after_grouping']
[ 2024-02-26 14:16:31,747 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:16:31] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2024-02-26 14:16:31,751 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:16:31] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2024-02-26 14:16:41,273 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:16:41] "GET /predictdata HTTP/1.1" 200 -
[ 2024-02-26 14:16:41,550 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:16:41] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2024-02-26 14:16:56,587 ] 828 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "d:\ML\github\ML-Example-docker-image\src\pipeline\predict_pipeline.py", line 18, in predict
    data_scaled=preprocessor.transform(features)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\_set_output.py", line 295, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1014, in transform
    Xs = self._call_func_on_transformers(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py", line 823, in _call_func_on_transformers
    return Parallel(n_jobs=self.n_jobs)(jobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\parallel.py", line 67, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\joblib\parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\joblib\parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\parallel.py", line 129, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\pipeline.py", line 1283, in _transform_one
    res = transformer.transform(X, **params.transform)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\pipeline.py", line 905, in transform
    Xt = transform.transform(Xt, **routed_params[name].transform)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\utils\_set_output.py", line 295, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1032, in transform
    if self._drop_idx_after_grouping is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OneHotEncoder' object has no attribute '_drop_idx_after_grouping'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ML\github\ML-Example-docker-image\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ML\github\ML-Example-docker-image\app.py", line 36, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ML\github\ML-Example-docker-image\src\pipeline\predict_pipeline.py", line 23, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [d:\ML\github\ML-Example-docker-image\src\pipeline\predict_pipeline.py] line number [18] error message['OneHotEncoder' object has no attribute '_drop_idx_after_grouping']
[ 2024-02-26 14:16:56,591 ] 96 werkzeug - INFO - 127.0.0.1 - - [26/Feb/2024 14:16:56] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
